use_frameworks!

platform :ios, '9.0'

target 'RSTableReloadAnimation_Example' do
  pod 'RSTableReloadAnimation', :path => '../'

  target 'RSTableReloadAnimation_Tests' do
    inherit! :search_paths

    
  end
end
